### ISSUE TITLE
newbie

### ISSUE THREAD

**Issue by orefalo** [AppsFlyer/wrk3#8]
Hi..
Sorry to ask, I am no golang expert

found this project while I was looking for wrk2 on M1 arm

trying to compile, it runs, no errors, but where is the exe?

am I doing anything wrong?

**Comment by eranharel** [comment]
Hi @orefalo, 

We built this as a library to help benchmark code like gRPC services, or any other service that doesn't have an HTTP API, thus can not be tested with wrk2.

We never got to properly productise it, and create a main function for it.

You can call the `BenchmarkCmd` from your main to create a benchmark, providing it a request function, or use it as an example.

Hope this helps

**Comment by orefalo** [comment]
Thank you
